assignment2_awm/assignment2_awm/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mosques_near_me.urls', namespace='mosques_near_me')),
    path('', include('pwa.urls')),

]

assignment2_awm/mosques_near_me/urls.py
from django.urls import path
from django.views.generic import TemplateView

from mosques_near_me import views

app_name = "mosques_near_me"

urlpatterns = [

    path('register/', views.register_user, name='register_user'),
    path('registersuccess/', TemplateView.as_view(template_name='user_registration/register_success.html'), name="success"),
    path('login/', views.user_login, name='login'),
    path('home/', TemplateView.as_view(template_name='index.html'), name="home"),
    path('logout/', TemplateView.as_view(template_name='user_registration/logout.html'), name='logout'),
    path('map/', TemplateView.as_view(template_name='view_map.html'), name='map'),
    path('menu/', TemplateView.as_view(template_name='user_menu.html'), name='menu'),
    path('update/', views.update_location, name="update_location"),
    path('findmosques/', views.find_mosque, name="findmosques"),
    path('addFavourites/', views.addFavouriteMosque, name="favouriteMosque"),
    path('profile/', views.getFavouriteMosque, name="profile"),
    path('prayertimes/', TemplateView.as_view(template_name="prayer_times.html"), name="prayertimes"),

]

assignment2_awm/mosques_near_me/models.py
# Create your models here.
from django.contrib.auth.models import User
from django.contrib.gis.db import models


class WorldBorder(models.Model):
    # Regular Django fields corresponding to the attributes in the
    # world borders shapefile.
    name = models.CharField(max_length=50)
    area = models.IntegerField()
    pop2005 = models.IntegerField('Population 2005')
    fips = models.CharField('FIPS Code', max_length=2, null=True)
    iso2 = models.CharField('2 Digit ISO', max_length=2)
    iso3 = models.CharField('3 Digit ISO', max_length=3)
    un = models.IntegerField('United Nations Code')
    region = models.IntegerField('Region Code')
    subregion = models.IntegerField('Sub-Region Code')
    lon = models.FloatField()
    lat = models.FloatField()

    # GeoDjango-specific: a geometry field (MultiPolygonField)
    mpoly = models.MultiPolygonField()

    # Returns the string representation of the model.
    def __str__(self):
        return self.name


# Extending in-built user model with one-to-one relationship
class UserProfile(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    username = models.CharField(max_length=50, primary_key=True)
    email = models.CharField(max_length=50, null=True)
    user_location = models.PointField(null=True)


class Mosques(models.Model):
    location = models.CharField(max_length=100, null=True)
    mosque_goer = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    mosque_name = models.CharField(max_length=100, null=True)
    mosque_map_location = models.PointField(null=True)

assignment2_awm/mosques_near_me/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegisterUserForm(UserCreationForm):
    email = forms.EmailField(required=True)
    username = forms.CharField(max_length=50)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(RegisterUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        user.username = self.cleaned_data['username']

        if commit:
            user.save()
        return user

assignment2_awm/mosques_near_me/views.py
import json

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.gis.geos import Point, Polygon
from django.http import JsonResponse
from django.shortcuts import redirect

from .models import UserProfile, Mosques
from .forms import RegisterUserForm
from django.shortcuts import render
import overpy


def user_login(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)

        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect("mosques_near_me:menu")
            else:
                redirect("mosques_near_me:home")
        else:
            redirect("mosques_near_me:home")
            return render(request=request, template_name="user_registration/login.html", context={"login_form": form})
    else:
        form = AuthenticationForm()
        return render(request=request, template_name="user_registration/login.html", context={"login_form": form})


# Create your views here.
def register_user(request):
    if request.method == "POST":
        form = RegisterUserForm(request.POST)

        if form.is_valid():
            new_user = form.save()
            username = request.POST.get('username')
            email = request.POST.get('email')
            new_profile = UserProfile(user=new_user, username=username, email=email)
            new_profile.save()
            return redirect("mosques_near_me:success")
        else:
            return redirect("mosques_near_me:home")
    else:
        form = RegisterUserForm()
    return render(request=request, template_name="user_registration/register.html", context={"signup_form": form})


@login_required
def logout_request(request):
    logout(request)
    return redirect("mosques_near_me:home")


@login_required
def update_location(request):
    current_location = request.POST.get("userlocation", None)
    if not current_location:
        return JsonResponse({"message": "No location found."}, status=400)

    try:
        profile = request.user.userprofile

        if not profile:
            raise ValueError("Can't get user profile")

        coordinates = [float(coordinate) for coordinate in current_location.split(',')]
        profile.user_location = Point(coordinates, srid=4326)
        profile.save()

        update_msg = f'Update current location for {request.user.username} to {coordinates}'

        return JsonResponse({"message": update_msg}, status=200)
    except:
        return JsonResponse({"Error: ": "No Location found"}, status=400)

@login_required
def find_mosque(request):
    try:
        api = overpy.Overpass()
        bounding_box = request.POST.get("bbox", None)
        print("BBOX: ", bounding_box)

        # changing the bounding box to have the correct coords in the right place
        if bounding_box:
            bbox = bounding_box.split(",")

            shuffled_bbox = [bbox[1], bbox[0], bbox[3], bbox[2]]
            mod_boundingbox = [float(item) for item in shuffled_bbox]
            bounding_box = mod_boundingbox
        print(bounding_box)

        # query to find all the mosques within the bounding box of the map
        result = api.query(f"""
        [out:json];
        (
            node["amenity"="place_of_worship"]["religion"="muslim"]{tuple(bounding_box)};
            way["amenity"="place_of_worship"]["religion"="muslim"]{tuple(bounding_box)};
            relation["amenity"="place_of_worship"]["religion"="muslim"]{tuple(bounding_box)};
        );
        out body;
        >;
        out skel qt;
        """)

        # if no mosques are returned
        if len(result.nodes) == 0:
            return JsonResponse({"message": "There are no mosques near your location"})

        print("NODES: ", len(result.nodes))

        geojson_result = {

            "type": "FeatureCollection",
            "features": [],
        }

        nodes_in_way = []

        for way in result.ways:
            geojson_feature = {

                "type": "Feature",
                "id": "",
                "geometry": "",
                "properties": {}
            }

            poly = []
            for node in way.nodes:
                nodes_in_way.append(node.id)
                poly.append([float(node.lon), float(node.lat)])

                try:
                    poly = Polygon(poly)
                except:
                    continue

                geojson_feature["id"] = f"way_{way.id}"
                geojson_feature["geometry"] = json.loads(poly.centroid.geojson)
                geojson_feature["properties"] = {}

                for k, v in way.tags.items():
                    geojson_feature["properties"][k] = v
                    # print(geojson_feature)

                geojson_result["features"].append(geojson_feature) # adding all the information of the mosque to the geojson object

                # looping over all the mosques returned in the query
                for node in result.nodes:
                    if node.id in nodes_in_way:
                        continue

                    geojson_feature = {
                        "type": "Feature",
                        "id": "",
                        "geometry": "",
                        "properties": {}
                    }

                    point = Point([float(node.lon), float(node.lat)])
                    geojson_feature["id"] = f"node_{node.id}"
                    geojson_feature["geometry"] = json.loads(point.geojson)
                    geojson_feature["properties"] = {}
                    for k, v in node.tags.items():
                        geojson_feature["properties"][k] = v

                    geojson_result["features"].append(geojson_feature)

        return JsonResponse(geojson_result, status=200)
    except Exception as e:
        return JsonResponse({"message": f"Error: {e}."}, status=400)


@login_required
def addFavouriteMosque(request):

    try:
        mosque_name = request.POST.get("mosqueName", None)
        mosque_address = request.POST.get("mosqueCity", None)
        latitude = request.POST.get("lat", None)
        longitude = request.POST.get("long", None)
        mosque_coords = [float(latitude), float(longitude)]
        print("Mosque: ", mosque_name)
        user = request.user

        favourite_mosque = Mosques(mosque_name=mosque_name, mosque_goer=user, location=mosque_address)
        favourite_mosque.mosque_map_location = Point(mosque_coords, srid=4326)
        favourite_mosque.save()
        update_msg = f'{mosque_name} has been added to your list of favourite mosques'

        return JsonResponse({"message": update_msg}, status=200)

    except Exception as e:
        return JsonResponse({"Error": f"No mosque found near your area {e}"}, status=400)


# View which retrieves the current users list of favourite mosques
@login_required()
def getFavouriteMosque(request):
    if request.method == "GET":
        favourite_mosque = Mosques.objects.filter(mosque_goer=request.user)
        return render(request=request, template_name="user_profile.html", context={"favourite_mosques": favourite_mosque})

assignment2_awm/mosques_near_me/templates/base.html
{% load leaflet_tags %}
{% load static %}
{% load pwa %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% progressive_web_app_meta %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>{% block title %}App Base Template{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
     <script src="https://unpkg.com/leaflet@1.9.2/dist/leaflet.js"
     integrity="sha256-o9N1jGDZrf5tS+Ft4gbIK7mYMipq9lqpVJ91xHSyKhg="
     crossorigin=""></script>
    <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Varela+Round&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="manifest" href="manifest.json">
    {% leaflet_css %}
    {% leaflet_js %}
</head>
<body>
    <main>
        {% block content %}
        {% endblock %}

    </main>

    <footer class="bg-info text-center text-lg-start">
        <div class="text-center p-3" id="footer-div">AWM 2023 Assignment Wedaad Haruna</div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.5.1.min.js"
            integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
            crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
            integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
            crossorigin="anonymous"></script>

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
            integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
            crossorigin="anonymous"></script>

</body>
</html>

assignment2_awm/mosques_near_me/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>{% block title %}Mosques Near Me{% endblock %}</title>
</head>
<body>
     <nav class="navbar navbar-expand-md bg-info navbar-dark">
          <ul class="navbar-nav mr-auto">
              <li class="nav-item">
                   <a class="navbar-brand" href="#">Find a Mosque</a>
              </li>

          </ul>
     </nav>

        <h1 class="text-center">Mosques Near Me</h1>
        <div class="index-container">
            <img src="{% static 'images/mosque.png' %}" alt="map image" id="index-icon"/>
        </div>

        <div class="index-btn-container">
            <a href="{% url 'mosques_near_me:login' %}" class="ml-3 btn btn-lg active" role="button" aria-pressed="true" id="button-colors">Login</a>
            <a href="{% url 'mosques_near_me:register_user' %}" class="ml-3 btn btn-lg active" role="button" aria-pressed="true" id="button-colors">Register</a>
        </div>

    {% endblock %}
</body>
</html>

assignment2_awm/mosques_near_me/templates/prayer_times.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Prayer Times</title>
</head>
<body>
 <nav class="navbar navbar-expand-md bg-info navbar-dark">
      <ul class="navbar-nav mr-auto">
         {% if user.is_authenticated %}
          <a class="navbar-brand" href="#">Find a Mosque</a>

             <li class="nav-item">
                     <a class="nav-link" href="{% url 'mosques_near_me:menu' %}">Menu</a>
             </li>

             <li class="nav-item">
                 <a class="nav-link" href="{% url 'mosques_near_me:map' %}">Find Mosque</a>
             </li>

             <li class="nav-item">
                     <a class="nav-link" href="{% url 'mosques_near_me:prayertimes' %}">Prayer Times</a>
             </li>

             <li class="nav-item">
                     <a class="nav-link" href="{% url 'mosques_near_me:profile' %}">User Profile</a>
             </li>

             </ul>
             <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                     <a class="nav-link disabled" href="#" >Hello {{user.username}}!</a>
                </li>

                 <li class="nav-item">
                     <a class="nav-link" href="{% url 'mosques_near_me:logout' %}">Log Out</a>
                 </li>
             </ul>
         {% else %}
        <ul>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'mosques_near_me:login' %}">Login</a>
             </li>
         {% endif %}
      </ul>
    </nav>

        <h2 class="text-center m-3">Prayer Times</h2>

        <div class="div-container">
            <div class="menu-divs">
               <img src="{% static 'images/prayer-mat.png' %}" alt="prayer-mat"/>
            </div>

            <div class="menu-divs">
              <iframe style="width: 500px; height: 400px; border: 1px solid #ddd;" src="https://www.islamicfinder.org/prayer-widget/"> </iframe>
            </div>

        </div>
    {% endblock content %}
</body>
</html>

assignment2_awm/mosques_near_me/templates/user_menu.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>{% block title %}User Logout{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
     <nav class="navbar navbar-expand-md bg-info navbar-dark">
      <ul class="navbar-nav mr-auto">
         {% if user.is_authenticated %}
          <a class="navbar-brand" href="#">Find a Mosque</a>

             <li class="nav-item">
                     <a class="nav-link" href="{% url 'mosques_near_me:menu' %}">Menu</a>
             </li>

             <li class="nav-item">
                 <a class="nav-link" href="{% url 'mosques_near_me:map' %}">Find Mosque</a>
             </li>

             <li class="nav-item">
                     <a class="nav-link" href="{% url 'mosques_near_me:prayertimes' %}">Prayer Times</a>
             </li>

             <li class="nav-item">
                     <a class="nav-link" href="{% url 'mosques_near_me:profile' %}">User Profile</a>
             </li>

             </ul>
             <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                     <a class="nav-link disabled" href="#" >Hello {{user.username}}!</a>
                </li>

                 <li class="nav-item">
                     <a class="nav-link" href="{% url 'mosques_near_me:logout' %}">Log Out</a>
                 </li>
             </ul>
         {% else %}
        <ul>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'mosques_near_me:login' %}">Login</a>
             </li>
         {% endif %}
      </ul>
    </nav>

        <h2 class="text-center m-3">Find a Mosque Near You - Main Menu</h2>
        <p class="msg text-center">Welcome, {{user.username}}</p>

        <div class="div-container">
            <div class="menu-divs">
                <img src="{% static 'images/mosque2.png' %}" alt="locator marker" id="icon-style"/>
                <p class="msg">View map and find some local mosques!</p>
                <a href="{% url 'mosques_near_me:map' %}" class="btn" role="button" aria-pressed="true" id="button-colors">Find a Mosque</a>
            </div>

            <div class="menu-divs">
                <img src="{% static 'images/profile-avatar.png' %}" alt="locator marker" id="icon-style"/>
                <p class="msg">Your Profile</p>
                <a href="{% url 'mosques_near_me:profile' %}" class="btn" role="button" aria-pressed="true" id="button-colors">User Profile</a>
            </div>
        </div>
    {% endblock content %}

</body>
</html>

assignment2_awm/mosques_near_me/templates/user_profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>User Profile</title>
</head>
<body>
    <nav class="navbar navbar-expand-md bg-info navbar-dark">
      <ul class="navbar-nav mr-auto">
         {% if user.is_authenticated %}
          <a class="navbar-brand" href="#">Find a Mosque</a>

             <li class="nav-item">
                     <a class="nav-link" href="{% url 'mosques_near_me:menu' %}">Menu</a>
             </li>

             <li class="nav-item">
                 <a class="nav-link" href="{% url 'mosques_near_me:map' %}">Find Mosque</a>
             </li>

             <li class="nav-item">
                     <a class="nav-link" href="{% url 'mosques_near_me:prayertimes' %}">Prayer Times</a>
             </li>

             <li class="nav-item">
                     <a class="nav-link" href="{% url 'mosques_near_me:profile' %}">User Profile</a>
             </li>

             </ul>
             <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                     <a class="nav-link disabled" href="#" >Hello {{user.username}}!</a>
                </li>

                 <li class="nav-item">
                     <a class="nav-link" href="{% url 'mosques_near_me:logout' %}">Log Out</a>
                 </li>
             </ul>
         {% else %}
        <ul>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'mosques_near_me:login' %}">Login</a>
             </li>
         {% endif %}
      </ul>
    </nav>

        <h2 class="text-center m-3">Your Profile</h2>

        <div class="div-container">
            <div class="menu-divs">
               <img src="{% static 'images/avatar.png' %}" alt="profile picture place holder image" id="profile-icon"/>
                <p class="msg">Username: {{user.username}}</p>
            </div>

        <div class="menu-divs">
               <h5>Your Favourite Mosques:</h5>
                <ul>
                {% for mosque in favourite_mosques %}
                    <li>{{ mosque.mosque_name }}</li>
                    {% empty %}
                    <p>You don't have any mosques added to your favourites yet!</p>
                {% endfor %}
                </ul>
            </div>
        </div>
    {% endblock content %}
</body>
</html>

assignment2_awm/mosques_near_me/templates/view_map.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    {% load leaflet_tags %}
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <script src="https://unpkg.com/leaflet-routing-machine@latest/dist/leaflet-routing-machine.js"></script>
    <link rel="stylesheet" href="https://unpkg.com/leaflet-routing-machine@latest/dist/leaflet-routing-machine.css"/>
    <title>{% block title %}Map Page{% endblock %}</title>
</head>
<body>
     <nav class="navbar navbar-expand-md bg-info navbar-dark">
      <ul class="navbar-nav mr-auto">
         {% if user.is_authenticated %}
          <a class="navbar-brand" href="#">Find a Mosque</a>

             <li class="nav-item">
                     <a class="nav-link" href="{% url 'mosques_near_me:menu' %}">Menu</a>
             </li>

             <li class="nav-item">
                 <a class="nav-link" href="{% url 'mosques_near_me:map' %}">Find Mosque</a>
             </li>

             <li class="nav-item">
                     <a class="nav-link" href="{% url 'mosques_near_me:prayertimes' %}">Prayer Times</a>
             </li>

             <li class="nav-item">
                     <a class="nav-link" href="{% url 'mosques_near_me:profile' %}">User Profile</a>
             </li>

             </ul>
             <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                     <a class="nav-link disabled" href="#" >Hello {{user.username}}!</a>
                </li>

                 <li class="nav-item">
                     <a class="nav-link" href="{% url 'mosques_near_me:logout' %}">Log Out</a>
                 </li>
             </ul>
         {% else %}
        <ul>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'mosques_near_me:login' %}">Login</a>
             </li>
         {% endif %}
      </ul>
    </nav>

        <h3 class="text-center m-3">Your Location & Nearby Mosques</h3>

        <form method="post" action="{% url 'mosques_near_me:update_location' %}">
            {% csrf_token %}
        </form>

        <div id='map'></div>

        <script>
            let mosque_name = "";
            let mosque_address = "";
            let mosque_lat;
            let mosque_long;
            let userLat;
            let userLong;

            map = L.map('map', {doubleClickZoom: false}).locate({setView: true, maxZoom: 16});
            L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
                maxZoom: 19,
                attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'}).addTo(map);

            function onLocationFound(e) {

                let radius = e.accuracy;
                let lat = e.latlng.lat;
                let long  = e.latlng.lng;
                let location = e.latlng.lat + ", " + e.latlng.lng;

                L.marker(e.latlng).addTo(map)
                .bindPopup("Your Location: \n\nLat: " + lat + ", Long: " + long).openPopup();

                 L.circle(e.latlng, radius).addTo(map);

                userLat = lat;
                userLong = long;
                updateLocation(location);
                findMosque();
            }

            map.on('locationfound', onLocationFound);

            function getCookie(name) {
                let cookieValue = null;
                if (document.cookie && document.cookie !== '') {
                    const cookies = document.cookie.split(';');
                    for (let i = 0; i < cookies.length; i++) {
                        const cookie = cookies[i].trim();
                        // Does this cookie string begin with the name we want?
                        if (cookie.substring(0, name.length + 1) === (name + '=')) {
                            cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                            break;
                        }
                    }
                }
                return cookieValue;
            }

            function updateLocation(location) {

                console.log("In updatelocation(): " + location);
                let csrftoken = getCookie('csrftoken');

                $.ajax({
                    type: 'POST',
                    headers: {

                        'X-CSRFToken': csrftoken
                    },
                    url: '{% url 'mosques_near_me:update_location' %}',
                    data: {

                        userlocation: location
                    }
                }).done(function (data, status, xhr) {
                    console.log(data["message"])
                    {#let originalMsg = $(".toast-body").html();#}
                    {#$(".toast-body").html(originalMsg + "<br/>Updateddatabase<br/>" + data["message"]);#}
                }).fail(function (xhr, status, error) {
                    console.log(error);
                    {#let originalMsg = $(".toast-body").html();#}
                    {#$(".toast-body").html(originalMsg + "<br/>" + error);#}
                }).always(function () {
                    console.log("updateLocation() finished");
                    $(".toast").toast('show');
                });

            }

            // finding a mosque
            function findMosque() {
                console.log("In findMosque(): ");
                let csrftoken = getCookie('csrftoken');

                let bbox = map.getBounds().toBBoxString()
                console.log("bbox: " + bbox);

                $.ajax({
                    type: "POST",
                    url: '{% url 'mosques_near_me:findmosques' %}',
                    headers: {

                        'X-CSRFToken': csrftoken
                    },
                    data: {

                        bbox: map.getBounds().toBBoxString()
                    }
                }).done(function (data, status, xhr) {

                    console.log(data);

                    let markerStyle = {
                        radius: 20,
                        fillColor: "purple",
                        color: "purple",
                        weight: 1,
                        opacity: 1,
                        fillOpacity: 0.5
                    }

                    // Handle GeoJSON response from the server
                    let geoJsonLayer = L.geoJson(data, {

                        pointToLayer: function (feature, latlng) {
                            let marker = L.circleMarker(latlng, markerStyle);
                            mosque_name = feature.properties.name
                            mosque_address = "" + feature.properties["addr:city"]
                            mosque_lat = "" + feature.geometry.coordinates[0]
                            mosque_long = "" + feature.geometry.coordinates[1]
                            marker.bindPopup("<h6>Mosque: </h6>" + "Name: " + mosque_name + "<br/>City: " + mosque_address + "<br/>" +
                            '<br/><button id="add-favs" class="btn btn-primary bg-info" onclick=addToFavourites() ' +
                                'type="submit">Add to Favourites</button></br></br><button class="btn btn-primary bg-info" onclick=viewPath()>View Path</button>')
                            return marker
                        },
                    }).addTo(map);

                    map.addLayer(geoJsonLayer);

                }).fail(function (xhr, status, error) {
                    var message = "OSM Overpass query failed.<br/>";
                    console.log("Status: " + xhr.status + " " + xhr.responseText);
                    {#showOkAlert(message);#}
                }).always(function () {
                    {#toggleCentredSpinner("hide");#}
                });
            }

            // adding mosque to favourites
            function addToFavourites() {

                console.log("inside addToFavourites() " + mosque_name + " " + mosque_address + " lat " + mosque_lat + " long " + mosque_long);
                let csrftoken = getCookie('csrftoken');

                $.ajax({
                    type: 'POST',
                    headers: {

                        'X-CSRFToken': csrftoken
                    },
                    url: '{% url 'mosques_near_me:favouriteMosque' %}',
                    data: {

                        mosqueName: mosque_name,
                        mosqueCity: mosque_address,
                        lat: mosque_lat,
                        long: mosque_long
                    }
                }).done(function (data, status, xhr) {
                    console.log(data["message"])

                }).fail(function (xhr, status, error) {
                    console.log(error);

                }).always(function () {
                    console.log("addToFavourites() finished");
                });

            }

            {#viewPath()#}

            function viewPath() {
                console.log("Inside viewPath")
                console.log("User: " + userLat + " " + userLong + " " + mosque_lat + " " + mosque_long)

                L.Routing.control({
                   waypoints: [
                       L.latLng(userLat, userLong), // users location
                       L.latLng(mosque_long, mosque_lat)  // the mosque clicked on location
                   ],
                    routeWhileDragging: false
                }).addTo(map);
            }
        </script>
{% endblock %}
</body>
</html>